/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as PublicIndexImport } from './routes/_public/index'
import { Route as PublicTeamImport } from './routes/_public/team'
import { Route as PublicReportIssueImport } from './routes/_public/report-issue'
import { Route as PublicRegisterImport } from './routes/_public/register'
import { Route as PublicMissionImport } from './routes/_public/mission'
import { Route as PublicLoginImport } from './routes/_public/login'
import { Route as PublicJoinImport } from './routes/_public/join'
import { Route as PublicFaqImport } from './routes/_public/faq'
import { Route as PublicContactImport } from './routes/_public/contact'
import { Route as PublicActivitiesImport } from './routes/_public/activities'
import { Route as PublicAboutImport } from './routes/_public/about'
import { Route as errors503Import } from './routes/(errors)/503'
import { Route as errors500Import } from './routes/(errors)/500'
import { Route as errors404Import } from './routes/(errors)/404'
import { Route as errors403Import } from './routes/(errors)/403'
import { Route as errors401Import } from './routes/(errors)/401'
import { Route as authSignUpImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2Import } from './routes/(auth)/sign-in-2'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordImport } from './routes/(auth)/forgot-password'
import { Route as PublicServicesIndexImport } from './routes/_public/services/index'
import { Route as AuthenticatedTeamsIndexImport } from './routes/_authenticated/teams/index'
import { Route as AuthenticatedTagsIndexImport } from './routes/_authenticated/tags/index'
import { Route as AuthenticatedFavoritesIndexImport } from './routes/_authenticated/favorites/index'
import { Route as AuthenticatedExploreIndexImport } from './routes/_authenticated/explore/index'
import { Route as AuthenticatedDashboardIndexImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedCommandsIndexImport } from './routes/_authenticated/commands/index'
import { Route as PublicServicesPassagersImport } from './routes/_public/services/passagers'
import { Route as PublicServicesLivreursImport } from './routes/_public/services/livreurs'
import { Route as PublicServicesFlotteImport } from './routes/_public/services/flotte'
import { Route as PublicServicesChauffeursImport } from './routes/_public/services/chauffeurs'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings/route'
import { Route as AuthenticatedDashboardSettingsIndexImport } from './routes/_authenticated/dashboard/settings/index'
import { Route as AuthenticatedDashboardSettingsSecurityImport } from './routes/_authenticated/dashboard/settings/security'
import { Route as AuthenticatedDashboardSettingsExportImport } from './routes/_authenticated/dashboard/settings/export'
import { Route as AuthenticatedDashboardSettingsDangerZoneImport } from './routes/_authenticated/dashboard/settings/danger-zone'
import { Route as AuthenticatedDashboardSettingsCommandDefaultsImport } from './routes/_authenticated/dashboard/settings/command-defaults'
import { Route as AuthenticatedDashboardSettingsAppearanceImport } from './routes/_authenticated/dashboard/settings/appearance'

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const PublicIndexRoute = PublicIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)

const PublicTeamRoute = PublicTeamImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PublicRoute,
} as any)

const PublicReportIssueRoute = PublicReportIssueImport.update({
  id: '/report-issue',
  path: '/report-issue',
  getParentRoute: () => PublicRoute,
} as any)

const PublicRegisterRoute = PublicRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)

const PublicMissionRoute = PublicMissionImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => PublicRoute,
} as any)

const PublicLoginRoute = PublicLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)

const PublicJoinRoute = PublicJoinImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => PublicRoute,
} as any)

const PublicFaqRoute = PublicFaqImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)

const PublicContactRoute = PublicContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)

const PublicActivitiesRoute = PublicActivitiesImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => PublicRoute,
} as any)

const PublicAboutRoute = PublicAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)

const errors503Route = errors503Import.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRoute,
} as any)

const errors500Route = errors500Import.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const errors404Route = errors404Import.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRoute,
} as any)

const errors403Route = errors403Import.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRoute,
} as any)

const errors401Route = errors401Import.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const authSignIn2Route = authSignIn2Import.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const authForgotPasswordRoute = authForgotPasswordImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const PublicServicesIndexRoute = PublicServicesIndexImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => PublicRoute,
} as any)

const AuthenticatedTeamsIndexRoute = AuthenticatedTeamsIndexImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedTagsIndexRoute = AuthenticatedTagsIndexImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedFavoritesIndexRoute =
  AuthenticatedFavoritesIndexImport.update({
    id: '/favorites/',
    path: '/favorites/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedExploreIndexRoute = AuthenticatedExploreIndexImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCommandsIndexRoute = AuthenticatedCommandsIndexImport.update(
  {
    id: '/commands/',
    path: '/commands/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const PublicServicesPassagersRoute = PublicServicesPassagersImport.update({
  id: '/services/passagers',
  path: '/services/passagers',
  getParentRoute: () => PublicRoute,
} as any)

const PublicServicesLivreursRoute = PublicServicesLivreursImport.update({
  id: '/services/livreurs',
  path: '/services/livreurs',
  getParentRoute: () => PublicRoute,
} as any)

const PublicServicesFlotteRoute = PublicServicesFlotteImport.update({
  id: '/services/flotte',
  path: '/services/flotte',
  getParentRoute: () => PublicRoute,
} as any)

const PublicServicesChauffeursRoute = PublicServicesChauffeursImport.update({
  id: '/services/chauffeurs',
  path: '/services/chauffeurs',
  getParentRoute: () => PublicRoute,
} as any)

const AuthenticatedDashboardSettingsRouteRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedDashboardSettingsIndexRoute =
  AuthenticatedDashboardSettingsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardSettingsRouteRoute,
  } as any)

const AuthenticatedDashboardSettingsSecurityRoute =
  AuthenticatedDashboardSettingsSecurityImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedDashboardSettingsRouteRoute,
  } as any)

const AuthenticatedDashboardSettingsExportRoute =
  AuthenticatedDashboardSettingsExportImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthenticatedDashboardSettingsRouteRoute,
  } as any)

const AuthenticatedDashboardSettingsDangerZoneRoute =
  AuthenticatedDashboardSettingsDangerZoneImport.update({
    id: '/danger-zone',
    path: '/danger-zone',
    getParentRoute: () => AuthenticatedDashboardSettingsRouteRoute,
  } as any)

const AuthenticatedDashboardSettingsCommandDefaultsRoute =
  AuthenticatedDashboardSettingsCommandDefaultsImport.update({
    id: '/command-defaults',
    path: '/command-defaults',
    getParentRoute: () => AuthenticatedDashboardSettingsRouteRoute,
  } as any)

const AuthenticatedDashboardSettingsAppearanceRoute =
  AuthenticatedDashboardSettingsAppearanceImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedDashboardSettingsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503Import
      parentRoute: typeof rootRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutImport
      parentRoute: typeof PublicImport
    }
    '/_public/activities': {
      id: '/_public/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof PublicActivitiesImport
      parentRoute: typeof PublicImport
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactImport
      parentRoute: typeof PublicImport
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqImport
      parentRoute: typeof PublicImport
    }
    '/_public/join': {
      id: '/_public/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof PublicJoinImport
      parentRoute: typeof PublicImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginImport
      parentRoute: typeof PublicImport
    }
    '/_public/mission': {
      id: '/_public/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof PublicMissionImport
      parentRoute: typeof PublicImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterImport
      parentRoute: typeof PublicImport
    }
    '/_public/report-issue': {
      id: '/_public/report-issue'
      path: '/report-issue'
      fullPath: '/report-issue'
      preLoaderRoute: typeof PublicReportIssueImport
      parentRoute: typeof PublicImport
    }
    '/_public/team': {
      id: '/_public/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof PublicTeamImport
      parentRoute: typeof PublicImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexImport
      parentRoute: typeof PublicImport
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_public/services/chauffeurs': {
      id: '/_public/services/chauffeurs'
      path: '/services/chauffeurs'
      fullPath: '/services/chauffeurs'
      preLoaderRoute: typeof PublicServicesChauffeursImport
      parentRoute: typeof PublicImport
    }
    '/_public/services/flotte': {
      id: '/_public/services/flotte'
      path: '/services/flotte'
      fullPath: '/services/flotte'
      preLoaderRoute: typeof PublicServicesFlotteImport
      parentRoute: typeof PublicImport
    }
    '/_public/services/livreurs': {
      id: '/_public/services/livreurs'
      path: '/services/livreurs'
      fullPath: '/services/livreurs'
      preLoaderRoute: typeof PublicServicesLivreursImport
      parentRoute: typeof PublicImport
    }
    '/_public/services/passagers': {
      id: '/_public/services/passagers'
      path: '/services/passagers'
      fullPath: '/services/passagers'
      preLoaderRoute: typeof PublicServicesPassagersImport
      parentRoute: typeof PublicImport
    }
    '/_authenticated/commands/': {
      id: '/_authenticated/commands/'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof AuthenticatedCommandsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/explore/': {
      id: '/_authenticated/explore/'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/favorites/': {
      id: '/_authenticated/favorites/'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/tags/': {
      id: '/_authenticated/tags/'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthenticatedTagsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/teams/': {
      id: '/_authenticated/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_public/services/': {
      id: '/_public/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PublicServicesIndexImport
      parentRoute: typeof PublicImport
    }
    '/_authenticated/dashboard/settings/appearance': {
      id: '/_authenticated/dashboard/settings/appearance'
      path: '/appearance'
      fullPath: '/dashboard/settings/appearance'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsAppearanceImport
      parentRoute: typeof AuthenticatedDashboardSettingsRouteImport
    }
    '/_authenticated/dashboard/settings/command-defaults': {
      id: '/_authenticated/dashboard/settings/command-defaults'
      path: '/command-defaults'
      fullPath: '/dashboard/settings/command-defaults'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsCommandDefaultsImport
      parentRoute: typeof AuthenticatedDashboardSettingsRouteImport
    }
    '/_authenticated/dashboard/settings/danger-zone': {
      id: '/_authenticated/dashboard/settings/danger-zone'
      path: '/danger-zone'
      fullPath: '/dashboard/settings/danger-zone'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsDangerZoneImport
      parentRoute: typeof AuthenticatedDashboardSettingsRouteImport
    }
    '/_authenticated/dashboard/settings/export': {
      id: '/_authenticated/dashboard/settings/export'
      path: '/export'
      fullPath: '/dashboard/settings/export'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsExportImport
      parentRoute: typeof AuthenticatedDashboardSettingsRouteImport
    }
    '/_authenticated/dashboard/settings/security': {
      id: '/_authenticated/dashboard/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsSecurityImport
      parentRoute: typeof AuthenticatedDashboardSettingsRouteImport
    }
    '/_authenticated/dashboard/settings/': {
      id: '/_authenticated/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsIndexImport
      parentRoute: typeof AuthenticatedDashboardSettingsRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedDashboardSettingsRouteRouteChildren {
  AuthenticatedDashboardSettingsAppearanceRoute: typeof AuthenticatedDashboardSettingsAppearanceRoute
  AuthenticatedDashboardSettingsCommandDefaultsRoute: typeof AuthenticatedDashboardSettingsCommandDefaultsRoute
  AuthenticatedDashboardSettingsDangerZoneRoute: typeof AuthenticatedDashboardSettingsDangerZoneRoute
  AuthenticatedDashboardSettingsExportRoute: typeof AuthenticatedDashboardSettingsExportRoute
  AuthenticatedDashboardSettingsSecurityRoute: typeof AuthenticatedDashboardSettingsSecurityRoute
  AuthenticatedDashboardSettingsIndexRoute: typeof AuthenticatedDashboardSettingsIndexRoute
}

const AuthenticatedDashboardSettingsRouteRouteChildren: AuthenticatedDashboardSettingsRouteRouteChildren =
  {
    AuthenticatedDashboardSettingsAppearanceRoute:
      AuthenticatedDashboardSettingsAppearanceRoute,
    AuthenticatedDashboardSettingsCommandDefaultsRoute:
      AuthenticatedDashboardSettingsCommandDefaultsRoute,
    AuthenticatedDashboardSettingsDangerZoneRoute:
      AuthenticatedDashboardSettingsDangerZoneRoute,
    AuthenticatedDashboardSettingsExportRoute:
      AuthenticatedDashboardSettingsExportRoute,
    AuthenticatedDashboardSettingsSecurityRoute:
      AuthenticatedDashboardSettingsSecurityRoute,
    AuthenticatedDashboardSettingsIndexRoute:
      AuthenticatedDashboardSettingsIndexRoute,
  }

const AuthenticatedDashboardSettingsRouteRouteWithChildren =
  AuthenticatedDashboardSettingsRouteRoute._addFileChildren(
    AuthenticatedDashboardSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardSettingsRouteRoute: typeof AuthenticatedDashboardSettingsRouteRouteWithChildren
  AuthenticatedCommandsIndexRoute: typeof AuthenticatedCommandsIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedExploreIndexRoute: typeof AuthenticatedExploreIndexRoute
  AuthenticatedFavoritesIndexRoute: typeof AuthenticatedFavoritesIndexRoute
  AuthenticatedTagsIndexRoute: typeof AuthenticatedTagsIndexRoute
  AuthenticatedTeamsIndexRoute: typeof AuthenticatedTeamsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardSettingsRouteRoute:
    AuthenticatedDashboardSettingsRouteRouteWithChildren,
  AuthenticatedCommandsIndexRoute: AuthenticatedCommandsIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedExploreIndexRoute: AuthenticatedExploreIndexRoute,
  AuthenticatedFavoritesIndexRoute: AuthenticatedFavoritesIndexRoute,
  AuthenticatedTagsIndexRoute: AuthenticatedTagsIndexRoute,
  AuthenticatedTeamsIndexRoute: AuthenticatedTeamsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicActivitiesRoute: typeof PublicActivitiesRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicJoinRoute: typeof PublicJoinRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicMissionRoute: typeof PublicMissionRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicReportIssueRoute: typeof PublicReportIssueRoute
  PublicTeamRoute: typeof PublicTeamRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicServicesChauffeursRoute: typeof PublicServicesChauffeursRoute
  PublicServicesFlotteRoute: typeof PublicServicesFlotteRoute
  PublicServicesLivreursRoute: typeof PublicServicesLivreursRoute
  PublicServicesPassagersRoute: typeof PublicServicesPassagersRoute
  PublicServicesIndexRoute: typeof PublicServicesIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicActivitiesRoute: PublicActivitiesRoute,
  PublicContactRoute: PublicContactRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicJoinRoute: PublicJoinRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicMissionRoute: PublicMissionRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicReportIssueRoute: PublicReportIssueRoute,
  PublicTeamRoute: PublicTeamRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicServicesChauffeursRoute: PublicServicesChauffeursRoute,
  PublicServicesFlotteRoute: PublicServicesFlotteRoute,
  PublicServicesLivreursRoute: PublicServicesLivreursRoute,
  PublicServicesPassagersRoute: PublicServicesPassagersRoute,
  PublicServicesIndexRoute: PublicServicesIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PublicRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/about': typeof PublicAboutRoute
  '/activities': typeof PublicActivitiesRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/join': typeof PublicJoinRoute
  '/login': typeof PublicLoginRoute
  '/mission': typeof PublicMissionRoute
  '/register': typeof PublicRegisterRoute
  '/report-issue': typeof PublicReportIssueRoute
  '/team': typeof PublicTeamRoute
  '/': typeof PublicIndexRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRouteRouteWithChildren
  '/services/chauffeurs': typeof PublicServicesChauffeursRoute
  '/services/flotte': typeof PublicServicesFlotteRoute
  '/services/livreurs': typeof PublicServicesLivreursRoute
  '/services/passagers': typeof PublicServicesPassagersRoute
  '/commands': typeof AuthenticatedCommandsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/explore': typeof AuthenticatedExploreIndexRoute
  '/favorites': typeof AuthenticatedFavoritesIndexRoute
  '/tags': typeof AuthenticatedTagsIndexRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
  '/services': typeof PublicServicesIndexRoute
  '/dashboard/settings/appearance': typeof AuthenticatedDashboardSettingsAppearanceRoute
  '/dashboard/settings/command-defaults': typeof AuthenticatedDashboardSettingsCommandDefaultsRoute
  '/dashboard/settings/danger-zone': typeof AuthenticatedDashboardSettingsDangerZoneRoute
  '/dashboard/settings/export': typeof AuthenticatedDashboardSettingsExportRoute
  '/dashboard/settings/security': typeof AuthenticatedDashboardSettingsSecurityRoute
  '/dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/about': typeof PublicAboutRoute
  '/activities': typeof PublicActivitiesRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/join': typeof PublicJoinRoute
  '/login': typeof PublicLoginRoute
  '/mission': typeof PublicMissionRoute
  '/register': typeof PublicRegisterRoute
  '/report-issue': typeof PublicReportIssueRoute
  '/team': typeof PublicTeamRoute
  '/': typeof PublicIndexRoute
  '/services/chauffeurs': typeof PublicServicesChauffeursRoute
  '/services/flotte': typeof PublicServicesFlotteRoute
  '/services/livreurs': typeof PublicServicesLivreursRoute
  '/services/passagers': typeof PublicServicesPassagersRoute
  '/commands': typeof AuthenticatedCommandsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/explore': typeof AuthenticatedExploreIndexRoute
  '/favorites': typeof AuthenticatedFavoritesIndexRoute
  '/tags': typeof AuthenticatedTagsIndexRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
  '/services': typeof PublicServicesIndexRoute
  '/dashboard/settings/appearance': typeof AuthenticatedDashboardSettingsAppearanceRoute
  '/dashboard/settings/command-defaults': typeof AuthenticatedDashboardSettingsCommandDefaultsRoute
  '/dashboard/settings/danger-zone': typeof AuthenticatedDashboardSettingsDangerZoneRoute
  '/dashboard/settings/export': typeof AuthenticatedDashboardSettingsExportRoute
  '/dashboard/settings/security': typeof AuthenticatedDashboardSettingsSecurityRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_public/about': typeof PublicAboutRoute
  '/_public/activities': typeof PublicActivitiesRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/join': typeof PublicJoinRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/mission': typeof PublicMissionRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/report-issue': typeof PublicReportIssueRoute
  '/_public/team': typeof PublicTeamRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRouteRouteWithChildren
  '/_public/services/chauffeurs': typeof PublicServicesChauffeursRoute
  '/_public/services/flotte': typeof PublicServicesFlotteRoute
  '/_public/services/livreurs': typeof PublicServicesLivreursRoute
  '/_public/services/passagers': typeof PublicServicesPassagersRoute
  '/_authenticated/commands/': typeof AuthenticatedCommandsIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/explore/': typeof AuthenticatedExploreIndexRoute
  '/_authenticated/favorites/': typeof AuthenticatedFavoritesIndexRoute
  '/_authenticated/tags/': typeof AuthenticatedTagsIndexRoute
  '/_authenticated/teams/': typeof AuthenticatedTeamsIndexRoute
  '/_public/services/': typeof PublicServicesIndexRoute
  '/_authenticated/dashboard/settings/appearance': typeof AuthenticatedDashboardSettingsAppearanceRoute
  '/_authenticated/dashboard/settings/command-defaults': typeof AuthenticatedDashboardSettingsCommandDefaultsRoute
  '/_authenticated/dashboard/settings/danger-zone': typeof AuthenticatedDashboardSettingsDangerZoneRoute
  '/_authenticated/dashboard/settings/export': typeof AuthenticatedDashboardSettingsExportRoute
  '/_authenticated/dashboard/settings/security': typeof AuthenticatedDashboardSettingsSecurityRoute
  '/_authenticated/dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/about'
    | '/activities'
    | '/contact'
    | '/faq'
    | '/join'
    | '/login'
    | '/mission'
    | '/register'
    | '/report-issue'
    | '/team'
    | '/'
    | '/dashboard/settings'
    | '/services/chauffeurs'
    | '/services/flotte'
    | '/services/livreurs'
    | '/services/passagers'
    | '/commands'
    | '/dashboard'
    | '/explore'
    | '/favorites'
    | '/tags'
    | '/teams'
    | '/services'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/command-defaults'
    | '/dashboard/settings/danger-zone'
    | '/dashboard/settings/export'
    | '/dashboard/settings/security'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/about'
    | '/activities'
    | '/contact'
    | '/faq'
    | '/join'
    | '/login'
    | '/mission'
    | '/register'
    | '/report-issue'
    | '/team'
    | '/'
    | '/services/chauffeurs'
    | '/services/flotte'
    | '/services/livreurs'
    | '/services/passagers'
    | '/commands'
    | '/dashboard'
    | '/explore'
    | '/favorites'
    | '/tags'
    | '/teams'
    | '/services'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/command-defaults'
    | '/dashboard/settings/danger-zone'
    | '/dashboard/settings/export'
    | '/dashboard/settings/security'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_public/about'
    | '/_public/activities'
    | '/_public/contact'
    | '/_public/faq'
    | '/_public/join'
    | '/_public/login'
    | '/_public/mission'
    | '/_public/register'
    | '/_public/report-issue'
    | '/_public/team'
    | '/_public/'
    | '/_authenticated/dashboard/settings'
    | '/_public/services/chauffeurs'
    | '/_public/services/flotte'
    | '/_public/services/livreurs'
    | '/_public/services/passagers'
    | '/_authenticated/commands/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/explore/'
    | '/_authenticated/favorites/'
    | '/_authenticated/tags/'
    | '/_authenticated/teams/'
    | '/_public/services/'
    | '/_authenticated/dashboard/settings/appearance'
    | '/_authenticated/dashboard/settings/command-defaults'
    | '/_authenticated/dashboard/settings/danger-zone'
    | '/_authenticated/dashboard/settings/export'
    | '/_authenticated/dashboard/settings/security'
    | '/_authenticated/dashboard/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_public",
        "/(auth)/forgot-password",
        "/(auth)/otp",
        "/(auth)/sign-in",
        "/(auth)/sign-in-2",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/dashboard/settings",
        "/_authenticated/commands/",
        "/_authenticated/dashboard/",
        "/_authenticated/explore/",
        "/_authenticated/favorites/",
        "/_authenticated/tags/",
        "/_authenticated/teams/"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/about",
        "/_public/activities",
        "/_public/contact",
        "/_public/faq",
        "/_public/join",
        "/_public/login",
        "/_public/mission",
        "/_public/register",
        "/_public/report-issue",
        "/_public/team",
        "/_public/",
        "/_public/services/chauffeurs",
        "/_public/services/flotte",
        "/_public/services/livreurs",
        "/_public/services/passagers",
        "/_public/services/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/(auth)/sign-in-2": {
      "filePath": "(auth)/sign-in-2.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.tsx"
    },
    "/_public/about": {
      "filePath": "_public/about.tsx",
      "parent": "/_public"
    },
    "/_public/activities": {
      "filePath": "_public/activities.tsx",
      "parent": "/_public"
    },
    "/_public/contact": {
      "filePath": "_public/contact.tsx",
      "parent": "/_public"
    },
    "/_public/faq": {
      "filePath": "_public/faq.tsx",
      "parent": "/_public"
    },
    "/_public/join": {
      "filePath": "_public/join.tsx",
      "parent": "/_public"
    },
    "/_public/login": {
      "filePath": "_public/login.tsx",
      "parent": "/_public"
    },
    "/_public/mission": {
      "filePath": "_public/mission.tsx",
      "parent": "/_public"
    },
    "/_public/register": {
      "filePath": "_public/register.tsx",
      "parent": "/_public"
    },
    "/_public/report-issue": {
      "filePath": "_public/report-issue.tsx",
      "parent": "/_public"
    },
    "/_public/team": {
      "filePath": "_public/team.tsx",
      "parent": "/_public"
    },
    "/_public/": {
      "filePath": "_public/index.tsx",
      "parent": "/_public"
    },
    "/_authenticated/dashboard/settings": {
      "filePath": "_authenticated/dashboard/settings/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/dashboard/settings/appearance",
        "/_authenticated/dashboard/settings/command-defaults",
        "/_authenticated/dashboard/settings/danger-zone",
        "/_authenticated/dashboard/settings/export",
        "/_authenticated/dashboard/settings/security",
        "/_authenticated/dashboard/settings/"
      ]
    },
    "/_public/services/chauffeurs": {
      "filePath": "_public/services/chauffeurs.tsx",
      "parent": "/_public"
    },
    "/_public/services/flotte": {
      "filePath": "_public/services/flotte.tsx",
      "parent": "/_public"
    },
    "/_public/services/livreurs": {
      "filePath": "_public/services/livreurs.tsx",
      "parent": "/_public"
    },
    "/_public/services/passagers": {
      "filePath": "_public/services/passagers.tsx",
      "parent": "/_public"
    },
    "/_authenticated/commands/": {
      "filePath": "_authenticated/commands/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/": {
      "filePath": "_authenticated/dashboard/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/explore/": {
      "filePath": "_authenticated/explore/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/favorites/": {
      "filePath": "_authenticated/favorites/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/tags/": {
      "filePath": "_authenticated/tags/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/teams/": {
      "filePath": "_authenticated/teams/index.tsx",
      "parent": "/_authenticated"
    },
    "/_public/services/": {
      "filePath": "_public/services/index.tsx",
      "parent": "/_public"
    },
    "/_authenticated/dashboard/settings/appearance": {
      "filePath": "_authenticated/dashboard/settings/appearance.tsx",
      "parent": "/_authenticated/dashboard/settings"
    },
    "/_authenticated/dashboard/settings/command-defaults": {
      "filePath": "_authenticated/dashboard/settings/command-defaults.tsx",
      "parent": "/_authenticated/dashboard/settings"
    },
    "/_authenticated/dashboard/settings/danger-zone": {
      "filePath": "_authenticated/dashboard/settings/danger-zone.tsx",
      "parent": "/_authenticated/dashboard/settings"
    },
    "/_authenticated/dashboard/settings/export": {
      "filePath": "_authenticated/dashboard/settings/export.tsx",
      "parent": "/_authenticated/dashboard/settings"
    },
    "/_authenticated/dashboard/settings/security": {
      "filePath": "_authenticated/dashboard/settings/security.tsx",
      "parent": "/_authenticated/dashboard/settings"
    },
    "/_authenticated/dashboard/settings/": {
      "filePath": "_authenticated/dashboard/settings/index.tsx",
      "parent": "/_authenticated/dashboard/settings"
    }
  }
}
ROUTE_MANIFEST_END */
